version: "3"

services:
  go-api:
    build:
      context: ./
      dockerfile: $PWD/Dockerfile
    restart: always
    volumes:
      - ./:/go/src/app
    ports:
      - 9119:8000
    depends_on: 
      - mongodb
    links: 
      - mongodb
    environment: 
      port: 9119

  mongodb:
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - 27017:27017
      