version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/local/go/src/app/src
      - /usr/local/go/src/app/src/public
    ports:
      - 9119:8000
    depends_on:
      - db
    links:
      - db
    environment:
      ACCESS_TOKEN_SECRET: "smxcua9hj38qnfdqedxwiq"
      REFRESH_TOKEN_SECRET: "daskdijqwddi21n"
      MONGO_DBNAME: "movie_ticket"
      MONGO_URI: "mongodb://db:27017"

  db:
    image: mongo
    volumes:
      - ./data:/data
