FROM golang:1.14-alpine AS build
RUN apk --no-cache add build-base git mercurial gcc
ENV GO111MODULE=on
WORKDIR /usr/local/go/src/app
RUN go get github.com/google/wire/cmd/wire
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN wire
RUN go build -o main

FROM alpine:1.14
RUN apk --no-cache add tzdata
ENV TZ Asia/Bangkok
WORKDIR /app
RUN mkdir -p /app/src/public
COPY --from=build /usr/local/go/src/app/main .
ENTRYPOINT ./main

EXPOSE 8000
