FROM golang:alpine AS build
RUN apk --no-cache add build-base git bzr mercurial gcc
ENV GO111MODULE=on
WORKDIR /usr/local/go/src/app
RUN go get github.com/google/wire/cmd/wire
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN wire
RUN go build -o main

FROM alpine
WORKDIR /app
COPY --from=build /usr/local/go/src/app/main .
ENTRYPOINT ./main

EXPOSE 8000