FROM golang:alpine AS build
RUN apk add --no-cache git mercurial gcc
ENV GO111MODULE=on
WORKDIR /usr/local/go/src/app
RUN go get github.com/google/wire/cmd/wire
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN wire
RUN go build -o main

FROM alpine
RUN apk add --no-cache tzdata
ENV TZ Asia/Bangkok
WORKDIR /app
RUN mkdir -p /app/src/public
COPY --from=build /usr/local/go/src/app/main .
ENTRYPOINT ./main

EXPOSE 8000
