version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/local/go/src/app/src
    ports:
      - 9119:8000
    depends_on:
      - db
    links:
      - db
    environment:
      port: 8000
      mongo_uri: "mongodb://db:27017"

  db:
    image: mongo
    volumes:
      - ./data:/data
