version: "3"

services:
  go-api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/go/src/app
    ports:
      - 9119:8000
    depends_on: 
      - mongodb
    links: 
      - mongodb
  mongodb:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
      - ./data:/data/db
    ports:
      - 27017:27017