// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/icecreamhotz/movie-ticket/configs"
	"github.com/icecreamhotz/movie-ticket/controllers"
	"github.com/icecreamhotz/movie-ticket/database"
	"time"
)

// Injectors from wire.go:

func InitialApplication(mongoURI string, timeout time.Duration) (App, error) {
	configDatabase := configs.NewConfig(mongoURI, timeout)
	client, err := database.NewDatabase(configDatabase)
	if err != nil {
		return App{}, err
	}
	serviceHandler := controllers.NewHandler(client)
	app := NewApplication(serviceHandler)
	return app, nil
}
